"""Ongoing tested / untested list for the GameCube library -> docs/GAME_STATUS.md.

Joins the dump's batch_results.jsonl with the catalogue metadata in data/gc_catalogue.json
(title, developer, publisher, genre - no descriptions) and classifies every disc:

    rips          models exported by a real parser (count, plugin/format, verified flag)
    scanned       only the structure scanner (gx) found geometry - unverified raw meshes
    textures      only standalone textures came out
    nothing       ran clean, no models or textures recognised
    skip          not a 3D-model game (compilation / puzzle / rhythm / emulated) - by genre
    untested      no result row yet (or the row errored)

usage: python tools/game_status.py "D:/3d dump/GameCube" [docs/GAME_STATUS.md]
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOGUE = ROOT / "data" / "gc_catalogue.json"

SKIP_GENRES = ("Puzzle", "Music", "Party", "Board", "Card", "Quiz", "Trivia", "Pinball")
SKIP_WORDS = re.compile(
    r"\b(collection|compilation|arcade treasures|museum|intellivision|karaoke|donkey konga|"
    r"dance dance|mega ?man (anniversary|x collection)|sonic (mega|gems)|nintendo puzzle|"
    r"pokemon box|pokemon channel|zelda.*collector|ocarina|animal crossing)\b",
    re.I,
)


def load_rows(out: Path) -> dict[str, dict]:
    p = out / "batch_results.jsonl"
    rows = {}
    if p.exists():
        for line in p.read_text(encoding="utf-8").splitlines():
            if line.strip():
                r = json.loads(line)
                rows[r["file"]] = r
    return rows


def load_catalogue() -> dict[str, dict]:
    if not CATALOGUE.exists():
        return {}
    return json.loads(CATALOGUE.read_text(encoding="utf-8"))


def classify(file: str, row: dict | None, meta: dict, fmts: str = "") -> str:
    title = (meta.get("title") or (row or {}).get("title") or file).lower()
    genre = meta.get("genre", "")
    primary = genre.split(";")[0].strip()
    if SKIP_WORDS.search(title) or primary in SKIP_GENRES:
        return "skip"
    if row is None or row.get("error"):
        return "untested"
    if row.get("exported"):
        return "scanned" if fmts and all(f.startswith("gx ") for f in fmts.split(", ")) else "rips"
    if row.get("textures"):
        return "textures"
    return "nothing"


def formats(row: dict, out: Path) -> str:
    """Plugin/format names that produced this disc's models (from its rip_results.json;
    the batch row only keeps truncated warning keys)."""
    if not row.get("exported"):
        return ""
    rr = out / (row.get("dir") or row.get("game_id") or "") / "rip_results.json"
    names: Counter = Counter()
    try:
        for m in json.loads(rr.read_text(encoding="utf-8")).get("models", []):
            if not m.get("out_rel"):
                continue
            tags = (w[8:].strip() for w in m.get("warnings", []) if w.startswith("format: "))
            fmt = next(tags, "J3D")
            names[fmt] += 1
    except (OSError, ValueError):
        return ""
    return ", ".join(f"{k} {v}" for k, v in names.most_common(4))


def build(out: Path, lib_files: list[str]) -> str:
    rows = load_rows(out)
    cat = load_catalogue()
    files = sorted(set(lib_files) | set(rows) | set(cat))
    table = []
    for f in files:
        row = rows.get(f)
        meta = cat.get(f, {})
        fmts = formats(row, out) if row else ""
        status = classify(f, row, meta, fmts)
        table.append((status, f, row, meta, fmts))
    counts = Counter(s for s, *_ in table)
    by_dev: dict[str, Counter] = defaultdict(Counter)
    for s, _f, _row, meta, _fmts in table:
        by_dev[meta.get("developer") or "?"][s] += 1

    lines = [
        "# GameCube library status",
        "",
        "Generated by `tools/game_status.py` from the dump's `batch_results.jsonl` and the",
        "catalogue in `data/gc_catalogue.json`. One line per disc; no game data, only counts.",
        "",
        f"**{len(table)} discs: {counts['rips']} rip models, {counts['scanned']} scanner-only, "
        f"{counts['textures']} textures only, "
        f"{counts['nothing']} nothing yet, {counts['skip']} skipped (not 3D-model games), "
        f"{counts['untested']} untested.**",
        "",
        "## Untested / nothing yet, by developer (the engine map)",
        "",
        "| developer | rips | textures | nothing | untested | skip |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    todo = lambda kv: -(kv[1]["nothing"] + kv[1]["untested"])  # noqa: E731
    for dev, c in sorted(by_dev.items(), key=todo)[:40]:
        if c["nothing"] + c["untested"] == 0:
            continue
        lines.append(
            f"| {dev} | {c['rips']} | {c['textures']} | {c['nothing']} | "
            f"{c['untested']} | {c['skip']} |"
        )
    lines += [
        "",
        "## Every disc",
        "",
        "| status | game | ID | developer | genre | models | formats | verified | note |",
        "|---|---|---|---|---|---:|---|---|---|",
    ]
    order = {"untested": 0, "nothing": 1, "textures": 2, "scanned": 3, "rips": 4, "skip": 5}
    for s, f, row, meta, fmts in sorted(table, key=lambda t: (order[t[0]], t[1].lower())):
        title = meta.get("title") or (row or {}).get("title") or f
        gid = (row or {}).get("game_id", "")
        exported = (row or {}).get("exported", "")
        verified = row is not None and (row.get("verified_unbuffered") or row.get("verified"))
        ver = "" if row is None else ("yes" if verified else "no")
        note = ""
        if row and row.get("error"):
            note = f"error: {row['error'][:60]}"
        elif row and row.get("failed"):
            note = f"{row['failed']} failed"
        lines.append(
            f"| {s} | {title} | {gid} | {meta.get('developer', '')} | "
            f"{meta.get('genre', '').split(';')[0]} | "
            f"{exported} | {fmts} | {ver} | {note} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    out = Path(argv[1]) if len(argv) > 1 else Path("D:/3d dump/GameCube")
    dest = Path(argv[2]) if len(argv) > 2 else ROOT / "docs" / "GAME_STATUS.md"
    lib = Path("D:/LaunchBox/Games/Nintendo GameCube")
    lib_files = [p.name for p in lib.glob("*-1.iso")] if lib.exists() else []
    dest.write_text(build(out, lib_files), encoding="utf-8")
    print(f"-> {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
